// Auto-generated from SPT allExtracts.json. Do not edit manually.
export const EXTRACTS_BY_LOCATION: Record<string, string[]> = {
  "bigmap": [
    "EXFIL_ZB013",
    "Dorms V-Ex",
    "ZB-1011",
    "Crossroads",
    "Old Gas Station",
    "Trailer Park",
    "RUAF Roadblock",
    "customs_sniper_exit",
    "Custom_scav_pmc",
    "Shack",
    "Beyond Fuel Tank",
    "Railroad To Military Base",
    "Old Road Gate",
    "Sniper Roadblock",
    "Railroad To Port",
    "Trailer Park Workers Shack",
    "Railroad To Tarkov",
    "RUAF Roadblock_scav",
    "Warehouse 17",
    "Factory Shacks",
    "Warehouse 4",
    "Old Azs Gate",
    "Factory Far Corner",
    "Administration Gate",
    "Military Checkpoint"
  ],
  "factory4_day": [
    "Cellars",
    "Gate 3",
    "Gate 0",
    "Gate m",
    "Gate_o",
    "Camera Bunker Door",
    "Office Window"
  ],
  "factory4_night": [
    "Cellars",
    "Gate 3",
    "Gate 0",
    "Gate m",
    "Gate_o",
    "Camera Bunker Door",
    "Office Window"
  ],
  "Interchange": [
    "SE Exfil",
    "NW Exfil",
    "PP Exfil",
    "Interchange Cooperation",
    "Hole Exfill",
    "Saferoom Exfil"
  ],
  "laboratory": [
    "lab_Elevator_Cargo",
    "lab_Elevator_Main",
    "lab_Vent",
    "lab_Elevator_Med",
    "lab_Under_Storage_Collector",
    "lab_Parking_Gate",
    "lab_Hangar_Gate"
  ],
  "Lighthouse": [
    "EXFIL_Train",
    " V-Ex_light",
    "tunnel_shared",
    "Alpinist_light",
    "Shorl_free",
    "Nothern_Checkpoint",
    "Coastal_South_Road",
    "Shorl_free_scav",
    "Scav_Coastal_South",
    "Scav_Underboat_Hideout",
    "Scav_Hideout_at_the_grotto",
    "Scav_Industrial_zone"
  ],
  "RezervBase": [
    "EXFIL_Train",
    "EXFIL_Bunker_D2",
    "EXFIL_Bunker",
    "Alpinist",
    "EXFIL_ScavCooperation",
    "EXFIL_vent",
    "Exit1",
    "Exit2",
    "Exit3",
    "Exit4"
  ],
  "Sandbox": [
    "Sandbox_VExit",
    "Unity_free_exit",
    "Scav_coop_exit",
    "Nakatani_stairs_free_exit",
    "Sniper_exit"
  ],
  "Shoreline": [
    "Shorl_V-Ex",
    "Road to Customs",
    "Road_at_railbridge",
    "Tunnel",
    "Lighthouse_pass",
    "Smugglers_Trail_coop",
    "Pier Boat",
    "RedRebel_alp",
    "Scav Road to Customs",
    "Lighthouse",
    "Wrecked Road",
    "RWing Gym Entrance",
    "Adm Basement"
  ],
  "TarkovStreets": [
    "E8_yard",
    "E7_car",
    "E1",
    "E4",
    "E2",
    "E3",
    "E5",
    "E6",
    "E9_sniper",
    "Exit_E10_coop",
    "E7",
    "scav_e2",
    "scav_e3",
    "scav_e4",
    "scav_e5",
    "scav_e7",
    "scav_e8"
  ],
  "Woods": [
    "Factory Gate",
    "RUAF Gate",
    "ZB-016",
    "ZB-014",
    "UN Roadblock",
    "South V-Ex",
    "Outskirts",
    "un-sec",
    "wood_sniper_exit",
    "Dead Man's Place",
    "The Boat",
    "Scav House",
    "East Gate",
    "Mountain Stash",
    "West Border",
    "Old Station",
    "RUAF Roadblock"
  ],
  "factory4": [
    "Cellars",
    "Gate 3",
    "Gate 0",
    "Gate m",
    "Gate_o",
    "Camera Bunker Door",
    "Office Window"
  ]
}
